repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: Format code with Black (temp)
        language_version: python3.13
        args: ['--line-length=88', '--target-version=py313']

fail_fast: false
